### ISSUE TITLE
Selection resets when cursor blinks

### ISSUE THREAD

**Issue by dlvhdr** [SKalt/git-cc#34]
Using up/down to select an item gets reset to the first item when the app re-renders as the cursor blinks.

**Comment by SKalt** [comment]
Interesting! ~~I'm not observing that in on any of my machines (iterm on mac and the default terminal app on ubuntu).  Could you provide reproduction steps?~~ reproduced with a fresh build.

**Comment by SKalt** [comment]
Thanks for the bug report! I'll cut a bugfix release momentarily.
