### ISSUE TITLE
Add to Scoop Installler or Winget Installer for Windows Support

### ISSUE THREAD

**Issue by RayyanNafees** [SKalt/git-cc#41]
Can the CLI be pushed to Winget or Scoop package managers for windows officially ?
so one can easily 
`scoop install git-cc`
or
`winget install git-cc`

For now the only option is to use `eget` which doesn't perform global updates

**Comment by SKalt** [comment]
Sure, I'll see if I can get to that over the weekend.

**Comment by SKalt** [comment]
Hey @RayyanNafees, I think I got a viable scoop setup working as of 8da1149. I don't have a Windows dev box handy; could you test the scoop install? The scoop metadata lives over in https://github.com/SKalt/scoop-git-cc/blob/main/git-cc.json.

**Comment by RayyanNafees** [comment]
Installation is working fine

@SKalt  can't find the cli in any of scoop buckets
![image](https://github.com/SKalt/git-cc/assets/59685062/66b7cd00-4f5a-4dcb-b478-3875d0c07bcc)

U need to submit a pull request to [main](https://github.com/ScoopInstaller/main) branch

**Comment by SKalt** [comment]
Looks like the main  require a higher degree of popularity before accepting PRs:
> For an app to be acceptable for the main bucket, it should be:
>
>   - a reasonably well-known and widely used developer tool (e.g. if it's a GitHub project, it should have at least 500 stars and 150 forks)
>
> -- https://github.com/ScoopInstaller/Scoop/wiki/Criteria-for-including-apps-in-the-main-bucket, retrieved 2024-06

I think the key to getting scoop.sh to index the package is adding a `scoop-bucket` topic to https://github.com/skalt/scoop-git-cc. If it isn't, then `scoop bucket add ...` will do for now :shrug:.

**Comment by RayyanNafees** [comment]
what about `extras` bucket ?

or `winget` installation ?

**Comment by SKalt** [comment]
https://scoop.sh/#/apps?q=git-cc&o=false
