### ISSUE TITLE
feature: add allow-empty option

### ISSUE THREAD

**Issue by suft** [SKalt/git-cc#42]
Implement https://git-scm.com/docs/git-commit/2.31.0#Documentation/git-commit.txt---allow-empty

`git cc --allow-empty`

**Comment by SKalt** [comment]
Alright, this should be ready in v0.2.4. Thanks for the catch!

**Comment by suft** [comment]
I was just about to start writing a fix 😄, that was fast.
Thanks for adding the feature!

**Comment by SKalt** [comment]
I appreciate the willingness to contribute! If you've already started looking at/fixing my less-than-polished code, I'm interested in any other improvements you've got in mind.
